/*
 * This program was created by Misha Donais
 * On october 10th 2018
 * To guess the rolls of a die
 */

/**
 *
 * @author misha
 */
public class diceGameForm extends javax.swing.JFrame {
    int totalRolls = 0;
    int totalCorrect = 0;
    int totalIncorrect = 0;
    int userGuess;
    int diceRoll;
    double percCorrect = 0;
    /**
     * Creates new form diceGameForm
     */
    public diceGameForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        headerlbl = new javax.swing.JLabel();
        instlbl1 = new javax.swing.JLabel();
        instlbl2 = new javax.swing.JLabel();
        userGuesslbl = new javax.swing.JLabel();
        userGuesstxt = new javax.swing.JTextField();
        diceRolllbl = new javax.swing.JLabel();
        rollValuelbl = new javax.swing.JLabel();
        rollslbl = new javax.swing.JLabel();
        correctlbl = new javax.swing.JLabel();
        incorrectlbl = new javax.swing.JLabel();
        percentlbl = new javax.swing.JLabel();
        correctValuelbl = new javax.swing.JLabel();
        rollsValuelbl = new javax.swing.JLabel();
        incorrectValuelbl = new javax.swing.JLabel();
        percentValuelbl = new javax.swing.JLabel();
        rollDiebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerlbl.setFont(new java.awt.Font("Felix Titling", 0, 16)); // NOI18N
        headerlbl.setForeground(new java.awt.Color(204, 51, 0));
        headerlbl.setText("Super Dice Guessing Game");

        instlbl1.setFont(new java.awt.Font("Felix Titling", 0, 16)); // NOI18N
        instlbl1.setForeground(new java.awt.Color(204, 51, 0));
        instlbl1.setText("Enter a number, from 1 to 6");

        instlbl2.setFont(new java.awt.Font("Felix Titling", 0, 16)); // NOI18N
        instlbl2.setForeground(new java.awt.Color(204, 51, 0));
        instlbl2.setText("and click roll to roll the dice");

        userGuesslbl.setFont(new java.awt.Font("Felix Titling", 0, 16)); // NOI18N
        userGuesslbl.setForeground(new java.awt.Color(204, 51, 0));
        userGuesslbl.setText("Your guess");

        userGuesstxt.setFont(new java.awt.Font("Felix Titling", 0, 16)); // NOI18N
        userGuesstxt.setForeground(new java.awt.Color(204, 51, 0));
        userGuesstxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userGuesstxtActionPerformed(evt);
            }
        });

        diceRolllbl.setFont(new java.awt.Font("Felix Titling", 0, 16)); // NOI18N
        diceRolllbl.setForeground(new java.awt.Color(204, 51, 0));
        diceRolllbl.setText("Dice roll");

        rollValuelbl.setFont(new java.awt.Font("Felix Titling", 0, 16)); // NOI18N
        rollValuelbl.setForeground(new java.awt.Color(204, 51, 0));

        rollslbl.setFont(new java.awt.Font("Felix Titling", 0, 16)); // NOI18N
        rollslbl.setForeground(new java.awt.Color(204, 51, 0));
        rollslbl.setText("Number of Rolls:");

        correctlbl.setFont(new java.awt.Font("Felix Titling", 0, 16)); // NOI18N
        correctlbl.setForeground(new java.awt.Color(204, 51, 0));
        correctlbl.setText("Number of correct guesses:");

        incorrectlbl.setFont(new java.awt.Font("Felix Titling", 0, 16)); // NOI18N
        incorrectlbl.setForeground(new java.awt.Color(204, 51, 0));
        incorrectlbl.setText("Number of incorrect guesses:");

        percentlbl.setFont(new java.awt.Font("Felix Titling", 0, 16)); // NOI18N
        percentlbl.setForeground(new java.awt.Color(204, 51, 0));
        percentlbl.setText("Percentage of correct guesses:");

        correctValuelbl.setFont(new java.awt.Font("Felix Titling", 0, 16)); // NOI18N
        correctValuelbl.setForeground(new java.awt.Color(204, 51, 0));

        rollsValuelbl.setFont(new java.awt.Font("Felix Titling", 0, 16)); // NOI18N
        rollsValuelbl.setForeground(new java.awt.Color(204, 51, 0));

        incorrectValuelbl.setFont(new java.awt.Font("Felix Titling", 0, 16)); // NOI18N
        incorrectValuelbl.setForeground(new java.awt.Color(204, 51, 0));

        percentValuelbl.setFont(new java.awt.Font("Felix Titling", 0, 16)); // NOI18N
        percentValuelbl.setForeground(new java.awt.Color(204, 51, 0));

        rollDiebtn.setFont(new java.awt.Font("Felix Titling", 0, 16)); // NOI18N
        rollDiebtn.setForeground(new java.awt.Color(153, 51, 0));
        rollDiebtn.setText("Roll Die");
        rollDiebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollDiebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(instlbl1)
                                        .addComponent(percentlbl)
                                        .addComponent(incorrectlbl)
                                        .addComponent(correctlbl)
                                        .addComponent(rollslbl))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(instlbl2))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(headerlbl)
                                .addGap(34, 34, 34)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userGuesslbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userGuesstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rollDiebtn)
                        .addGap(116, 116, 116)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(percentValuelbl, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                        .addComponent(incorrectValuelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(correctValuelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rollsValuelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(diceRolllbl)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(rollValuelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(headerlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(instlbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(instlbl2)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userGuesslbl)
                            .addComponent(diceRolllbl)
                            .addComponent(rollDiebtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userGuesstxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rollValuelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rollslbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rollsValuelbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(correctlbl)
                    .addComponent(correctValuelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(incorrectlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(incorrectValuelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(percentlbl)
                    .addComponent(percentValuelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userGuesstxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userGuesstxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userGuesstxtActionPerformed

    private void rollDiebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollDiebtnActionPerformed
        
        //Random Number Generator
        diceRoll = (int)Math.round(Math.random()*5+1)
                
        //Setting value of die roll on GUI
        rollValuelbl.setText(String.valueOf(diceRoll));
        
        //Taking value of input
        userGuess = Integer.parseInt(userGuesstxt.getText());
        
        //Tracking number of rolls
        totalRolls = totalRolls +1;
        
        //Correct or incorrect
        if (diceRoll == userGuess) {
        totalCorrect = totalCorrect + 1;   
    }
        else {
            totalIncorrect = totalIncorrect + 1;
        }
        
        //Correct percentage math
        percCorrect = ((double)totalCorrect/(double)totalRolls) * 100;
        
        //ROunding math for percCorrect
        percCorrect = percCorrect * 100;
        percCorrect = Math.round(percCorrect);
        percCorrect = percCorrect / 100;
        
        //Output labels
        rollsValuelbl.setText(String.valueOf(totalRolls));
        correctValuelbl.setText(String.valueOf(totalCorrect));
        incorrectValuelbl.setText(String.valueOf(totalIncorrect));
        percentValuelbl.setText(String.valueOf(percCorrect));
        
        
        
    }//GEN-LAST:event_rollDiebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(diceGameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(diceGameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(diceGameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diceGameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new diceGameForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel correctValuelbl;
    private javax.swing.JLabel correctlbl;
    private javax.swing.JLabel diceRolllbl;
    private javax.swing.JLabel headerlbl;
    private javax.swing.JLabel incorrectValuelbl;
    private javax.swing.JLabel incorrectlbl;
    private javax.swing.JLabel instlbl1;
    private javax.swing.JLabel instlbl2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel percentValuelbl;
    private javax.swing.JLabel percentlbl;
    private javax.swing.JButton rollDiebtn;
    private javax.swing.JLabel rollValuelbl;
    private javax.swing.JLabel rollsValuelbl;
    private javax.swing.JLabel rollslbl;
    private javax.swing.JLabel userGuesslbl;
    private javax.swing.JTextField userGuesstxt;
    // End of variables declaration//GEN-END:variables
}
